//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.01 at 12:03:32 AM CLT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tinet.cl/devops-kpi/")
package cl.tinet.devops.metrics.model;
